version: 2

jobs:
  build:
    docker:
      - image: rust:1.34.0-slim

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y clang cmake libsnappy-dev
            rustup component add rustfmt
            rustup component add clippy
      - run:
          name: Format
          command: cargo fmt --all -- --check
      - run:
          name: Check
          command: cargo check --all
      - run:
          name: Clippy
          command: cargo clippy --all
      - run:
          name: Build
          command: cargo build --all
      - run:
          name: Test
          command: cargo test --all
