name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check
      run: cargo check
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
